server:
  port: 8888

spring:
  cloud:
    config:
      server:
        native: #配置文件位置，存在本地
          search-locations: classpath:/shared
#        git: #配置文件位置，git上
#          uri: https://github.com/tianxiang2017/ce/config-repo
  profiles:
     active: native #激活本地存储
  security:
    user:
      name: user # HTTP Basice的默认密码是user
      password: ${CONFIG_SERVICE_PASSWORD:password}



